version: "3"

services:
  mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log