FROM rust:1.62.0 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path ./s.amqp

FROM scratch
COPY --from=builder /usr/local/cargo/bin/amqp /usr/local/bin/amqp
USER scratchuser
CMD ["amqp"]