FROM rust:1.62.0 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path ./s.grpc

FROM scratch
COPY --from=builder /usr/local/cargo/bin/grpc /usr/local/bin/grpc
USER scratchuser
CMD ["grpc"]