version: "3"

services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log

  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile.rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
