[package]
name = "mqtt_client"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = { version = "0.4.0" }
rumqttc = { version =  "0.13.0" }
tokio = { version = "1", features = ["full"] }
