[workspace]

members = [
    "app",
    "domain",
    "infra",
    "s.amqp",
    "s.grpc",
    "s.http",
    "s.mqtt",
    "s.dummy"
]


default-members = ["s.amqp", "s.mqtt", "s.grpc", "s.http", "s.dummy", "infra"]