[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
bytes = { version = "1.2.0", features = ["serde"] }
rumqttc = { version =  "0.13.0" }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = { version = "1.0.82" }
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.15"
tracing = "0.1.35"
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.3"