FROM rust:1.62.0 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path ./s.dump

FROM scratch
COPY --from=builder /usr/local/cargo/bin/dump /usr/local/bin/dump
USER scratchuser
CMD ["dump"]