FROM rust:1.62.0 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path ./s.dummy

FROM scratch
COPY --from=builder /usr/local/cargo/bin/dummy /usr/local/bin/dummy
USER scratchuser
CMD ["dummy"]