[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
infra = { path = "../infra" }
log = { version = "0.4.17" }
serde = { version = "1.0.140", features = ["derive"] }
opentelemetry = { version = "0.17.0" }
async-trait = { version = "0.1.56" }
