[package]
name = "amqp"
version = "0.1.0"
edition = "2021"


[dependencies]
infra = { path = "../infra" }
lapin = { version = "2.1.1" }
tokio = { version = "1.17.0", features = ["full"] }
futures-util = { version = "0.3.21"}