[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.1.0" }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = { version = "1.0.82" }
json = { version = "0.12.4" }