[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.8.0" }
prost = { version = "0.11.0" }
tokio = { versin = "1.7.0", features = ["macros", "rt-multi-thread"] }


[build-dependencies]
tonic-build = { version = "0.8.0" }
